### ISSUE TITLE
Repository name should be reconsidered

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt-l10n#10]
The name of this repository isn't really a good choice and worth reconsidering.

On the one hand it's a generic term and as such not very telling regarding its content.
More importantly it can for sure not be used by downstream. Some distributions will definitely establish a single package providing this translation repository as a whole. The current repository name will hence break the tradition to use downstream names pretty similar to the upstream ones, eventually a bunch of different downstream names will be used to describe this repository which can be expected to be unfavourable for end-users.

So I think renaming would make sense. Regarding an eventual new name 'lxqt-l10n' seems like a reasonable choice as similar ones are already used by many other projects, in particular KDE.

**Comment by agaida** [comment]
Full ACK

**Comment by palinek** [comment]
I also share this opinion.

**Comment by luis-pereira** [comment]
I'm all in favor.

## 

Luís Pereira
Sent from my Android
No dia 15 de Mai de 2016 21:13, "palinek" notifications@github.com
escreveu:

**Comment by jleclanche** [comment]
Again with the stuff that shouldve been raised in the ML long ago :/

This repo isn't supposed to be packaged separately - and if it does end up being packaged it doesn't have to have the same name as on Github. It's supposed to be pulled at download time and integrated into the build.

Packaging it is the wrong way to do it. It forces a dependency on _all_ the LXDE translations for someone that might just be pulling in a single component.

**Comment by palinek** [comment]
> This repo isn't supposed to be packaged separately

Why not? We've already discussed that this is the pure decision of the packager (if he/she wants to create separate _component_-i18n packages or the translations will be included in the _component_ package)

> It forces a dependency on all the LXDE translations for someone that might just be pulling in a single component.

Only in a case when the packager decides to create a "big bulk package", but this will certainly not happen (I suppose).

**Comment by agaida** [comment]
> Packaging it is the wrong way to do it. It forces a dependency on all the LXDE translations for someone that might just be pulling in a single component.

Simply wrong.

**Comment by jleclanche** [comment]
> Some distributions will definitely establish a single package providing this translation repository as a whole

**Comment by agaida** [comment]
But this will be a downstream descision - nothing more, nothing less. Ok, the release date is shifted, lets do some more bikeshedding.

**Comment by luis-pereira** [comment]
It's up to packager to decide how to do it, IMO.

**Comment by pmattern** [comment]
What ever we decide, the decision should be made before the next release.
As of that release the chosen name will start getting used widely. Moreover it can IMO be taken for granted that downstream will start implementing various different alternative names for this very same repository as nobody will use the generic name "translations".
And this is just the kind of clutter I'd want to avoid by opening this issue.

**Comment by pmattern** [comment]
@luis-pereira, @palinek 
Could you kindly have a look at my previous comment?

Meanwhile I think `lxqt-l10n` could be an appropriate name which is already used by Debian, too.
@palinek That whole translation was basically your work. So is there any chance you could help us realize this before release 0.11?

**Comment by palinek** [comment]
> @luis-pereira, @palinek 
> Could you kindly have a look at my previous comment?

I've read it back then, but haven't anything new to say. As I've said before, I'm also for the name `lxqt-*` (-translation, -l10n, -i18n ... or whatever)

> So is there any chance you could help us realize this before release 0.11?

Should the decision to rename the repo be made, I'm ready to help doing it.

**Comment by agaida** [comment]
i would suggest lxqt-l10n - keep it short and l10n is a common abbr. - and used in KDE to.
(Why the heck is abbreviation such a long word?)

**Comment by pmattern** [comment]
After reconsidering all aspects I think it is adequate to rename the repository to `lxqt-l10n`.

First I thought we should try and get several people to work on this in parallel as it seemed like a rather complex task. But the repository can simply be renamed and the main work will probably be to adjust the code of all other components to the new name.
@palinek
As for the latter you are without a doubt the expert as it was basically you who implemented all this. So I'd say feel free to start working on this issue if you so wish and don't hesitate to let us others know if you need any kind of help.

**Comment by palinek** [comment]
According to [the github's doc](https://help.github.com/articles/renaming-a-repository/) we can simply rename the repo and we're done :smile: (everything should work as all the "old links" should be redirected to the "new ones").

But to be 100% correct, we should also update the liblxqt -> lxde/liblxqt#103

... and that's it.

So now anyone with admin permisions to lxde/translations and write permisions to lxde/liblxqt can "push the button".

Should I do it?

**Comment by palinek** [comment]
I've pushed the button...
