### ISSUE TITLE
Can't login or create a new user for translations.

### ISSUE THREAD

**Issue by ghost** [lxde/lxqt-l10n#30]
Not sure what's [up](https://i.imgur.com/nF80KEa.png?1)

**Comment by pmattern** [comment]
Cannot confirm this right now. Are you still seeing the problem? If so, could you elaborate how to reproduce?

**Comment by pmattern** [comment]
Looking back probably one of the well-known problems with pootle.lxde.org.
Closing due to lack of feedback.
