### ISSUE TITLE
Translations on Weblate

### ISSUE THREAD

**Issue by ghost** [lxde/lxqt-l10n#345]
Hi,
Do you have a Weblate instance for .ts translation ?
https://docs.weblate.org/en/latest/formats.html#qt-linguist-ts
Hosted projects : https://hosted.weblate.org/projects/
Regards,

**Comment by yarons** [comment]
https://github.com/lxqt/lxqt/issues/1495

In progress.

**Comment by ghost** [comment]
Thank you @yarons :)
