### ISSUE TITLE
Untranslatable strings?

### ISSUE THREAD

**Issue by micrococo** [lxde/lxqt-l10n#350]
Hi.

I am not able to find the strings highlighted in red to translate them. 

##### Expected Behavior
The strings should be translatable.

##### Current Behavior
The strings seems to be missing in the translation files.

##### Possible Solution
Update the translation files.

##### System Information
* Distribution & Version:  openSUSE Tumbleweed + LXQt:Git repository
* Kernel: 4.16.9-1-default x86_64
* Qt Version: Qt 5.10.0
* libqtxdg Version: 3.2.0~git0.3d586ec
* lxqt-build-tools Version: 0.4.0
* Package version: 0.13.0~git0.5ada22d

![screenshot_01m](https://user-images.githubusercontent.com/7717273/40448159-01224484-5ed5-11e8-867d-f7f7be53ba01.jpeg)

![screenshot_02m](https://user-images.githubusercontent.com/7717273/40448170-07938ad0-5ed5-11e8-9762-2278f4c118aa.jpeg)

**Comment by micrococo** [comment]
With current translations files (2018-06-03), strings in the second image are now present. But the three strings in the first image seem to be not translatable. By using `grep` I've found that:

- _Files processed:_ and _Group_ are only present in libfm-qt/libfm-qt_fr.ts
- _Cannot copy file 'filename': not supported_ isn't present in any translation file

**Comment by agaida** [comment]
https://github.com/lxqt/lxqt/issues/1497 - i would suggest to stop until the fallout is removed - the changes can be merged into the new things. Plus: All *.ts files will be up to date.

**Comment by agaida** [comment]
ok - weblate is running, all projects are updated - so all things should be fine
